export const LOGIN_WAITING = 'LOGIN_WAITING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_SERVERLIST = 'LOGIN_SERVERLIST';
export const LOGIN_SELECT_SHARD = 'LOGIN_SELECT_SHARD';
export const LOGIN_SERVER_RELAY = 'LOGIN_SERVER_RELAY';
export const LOGIN_CHOOSE_CHAR = 'LOGIN_CHOOSE_CHAR';

export const LOGIN_RECV_CHAR_LIST = 'LOGIN_RECV_CHAR_LIST';

export const LOGIN_RECV_FEATURES = 'LOGIN_RECV_FEATURES';

export const LOGIN_SENT_VERSION = 'LOGIN_SENT_VERSION'; 
