export const LOGIN_WAITING = 'LOGIN_WAITING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_SERVERLIST = 'LOGIN_SERVERLIST';
export const LOGIN_SELECT_SHARD = 'LOGIN_SELECT_SHARD';

export const LOGIN_SERVER_RELAY = 'LOGIN_SERVER_RELAY';
