export const WORLD_ADD_MESSAGE = 'WORLD_ADD_MESSAGE';
export const WORLD_REMOVE_MESSAGE = 'WORLD_REMOVE_MESSAGE';

export const WORLD_UPDATE_SEASON = 'WORLD_UPDATE_SEASON';
export const WORLD_UPDATE_WEATHER = 'WORLD_UPDATE_WEATHER';

export const WORLD_UPDATE_LIGHT = 'WORLD_UPDATE_LIGHT';

export const WORLD_UPDATE_MAP = 'WORLD_UPDATE_MAP';
