export const NETWORK_UPDATE_CONNECTION_STATUS = 'NETWORK_UPDATE_CONNECTION_STATUS';
export const NETWORK_UPDATE_SEED = 'NETWORK_UPDATE_SEED';
export const NETWORK_UPDATE_SENT_LOGIN = 'NETWORK_UPDATE_SENT_LOGIN';
export const NETWORK_UPDATE_COMPRESSION = 'NETWORK_UPDATE_COMPRESSION';
export const NETWORK_UPDATE_SENT_RELOGIN = 'NETWORK_UPDATE_SENT_RELOGIN';
export const NETWORK_UPDATE_SET_RECONNECTING = 'NETWORK_UPDATE_SET_RECONNECTING';
