export const PLAYER_UPDATE_HEALTH = 'PLAYER_UPDATE_HEALTH';
export const PLAYER_UPDATE_SELF = 'PLAYER_UPDATE_SELF';
export const PLAYER_UPDATE_WARMODE = 'PLAYER_UPDATE_WARMODE';

export const PLAYER_UPDATE_STATS = 'PLAYER_UPDATE_STATS';
